### PR TITLE
Update values for build

### PR DESCRIPTION
**Pull request by westin-m**

### CODE REVIEW

**Comment by jennyf19** [comment]
This is looking great so far!

**Comment by jennyf19** [comment]
@westin-m we need to update the email alias from IdentityDevExDotnet@microsoft.com to idauthsdkmsidweb@microsoft.com in this yml file:   [notificationAlias: 'IdentityDevExDotnet@microsoft.com'](https://github.com/AzureAD/microsoft-identity-web/blob/5b6367526ae40acc0ecb76c6535c24c400cd769e/build/template-publish-analysis-and-cleanup.yaml#LL15C24-L15C57)

Thank you!

**Comment by jennyf19** [comment]
>     codebase: NewOrUpdate

You'll need to delete from lines 12 to 26 and add in these lines after inputs:
` GdnPublishTsaOnboard: false
 GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)/build/tsaConfig.json'`
so the new json file is picked up. 

---
Refers to: build/template-publish-analysis-and-cleanup.yaml:13 in 329ae9d. [](commit_id = 329ae9d31a28c980c9b8a7d40d420ac9e62724e4, deletion_comment = False)

**Comment by westin-m** [comment]
> You'll need to delete from lines 12 to 26 and add in these lines after inputs: ` GdnPublishTsaOnboard: false GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)/build/tsaConfig.json'` so the new json file is picked up.

Pushed these changes

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @westin-m 

Did you run a release build to test these changes?

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @westin-m

**Review by jmprieur — APPROVED** [review]
LGTM
thanks @westin-m

**Comment by jennyf19** [comment]
#2137

**Pull request merged**
