### PR TITLE
fix for response type in mergedoptions

### PR DESCRIPTION
**Pull request by jennyf19**
#1215

### CODE REVIEW

**Comment by jennyf19** [comment]
@jmprieur we need to do more here, fyi. i might wait to merge

**Review by jmprieur — APPROVED** [review]
LGTM
Let's do it only for ResponseType.

**Comment by jennyf19** [comment]
fixed.

---
In reply to: [671583673](https://github.com/AzureAD/microsoft-identity-web/pull/1227#issuecomment-671583673) [](http://example.com/codeflow?ancestors=671583673,671583673)

**Review by jmprieur — APPROVED** [review]
LGTM
thanks @jennyf19

**Pull request merged**
