### PR TITLE
Fix ServiceDescriptor access when Keyed Services are present

### LINKED ISSUE #2604: .NET 8 WebApi throws InvalidOperationException when keyed Services are registered before MS Identity Services are registered
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.15.2

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

In an .NET 8 ASP.NET Core WebApi, when keyed services are being added to the DI container before calling `AddAuthentication(builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"))`, the service throws an InvalidOperationException with message "Your service provider may not support keyed services" upon startup.

### Reproduction steps

1. Create a standard ASP.NET Core WebAPI with auth set to Microsoft Identity Platform
2. Create an empty Interface ISomeInterface : `interface ISomeInterface {}`
3. Create a class SomeConcreteClass that implements ISomeInterface: `class SomeConcreteClass: ISomeInterface {}
4. Add `builder.Services.AddKeyedSingleton<ISomeInterface, SomeConcreteClass>("A") *BEFORE* the call to `builder.Services.AddAuthentication(builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"))`
5. Run the application and see that it crashes
6. Move the line `builder.Services.AddKeyedSingleton<ISomeInterface, SomeConcreteClass>("A")` until after the `builder.Services.AddAuthentication()` call
7. Run the application and see that it starts up as expected

### Error message

InvalidOperationException with message "Your service provider may not support keyed services"

   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor() in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:line 1061
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType() in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:line 164
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c.<AddMicrosoftIdentityWebApiImplementation>b__3_0(ServiceDescriptor s) in /_/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs:line 151
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found) in /_/src/libraries/System.Linq/src/System/Linq/First.cs:line 115
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) in /_/src/libraries/System.Linq/src/System/Linq/First.cs:line 49
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApiImplementation(AuthenticationBuilder builder, Action`1 configureJwtBearerOptions, String jwtBearerScheme, Boolean subscribeToJwtBearerMiddlewareDiagnosticsEvents) in /_/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs:line 151
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApi(AuthenticationBuilder builder, IConfigurationSection configurationSection, String jwtBearerScheme, Boolean subscribeToJwtBearerMiddlewareDiagnosticsEvents) in /_/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs:line 84
   at Program.<Main>$(String[] args) in C:\Demo\WebApplication2\Program.cs:line 12
   

### Id Web logs

_No response_

### Relevant code snippets

```csharp
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Identity.Web;

var builder = WebApplication.CreateBuilder(args);

// if this line is *BEFORE* the `AddAuthentication` call, the app crashes at startup
// if this line is *AFTER* the `AddAuthentication` call, the app starts up as expected
builder.Services.AddKeyedSingleton<IMyInterface, MyConcreteType>("A");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"))
        .EnableTokenAcquisitionToCallDownstreamApi()
            .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
            .AddInMemoryTokenCaches();
builder.Services.AddAuthorization();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.Run();

internal interface IMyInterface
{
}

internal class MyConcreteType : IMyInterface
{
}
```

### Regression

_No response_

### Expected behavior

App starts up normally

### PR DESCRIPTION
**Pull request by ReubenBond**
# Fix ServiceDescriptor access when Keyed Services are present

- [x] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Fixes the use of `ServiceDescriptor` for containers which have keyed services present. This can be an issue on .NET 8.0 and has been reported by some users of the library here: https://github.com/AzureAD/microsoft-identity-web/issues/2604

## Description

The issue is caused by unconditional access to `ServiceDescriptor.ImplementationType` and the fix is to first check whether `ServiceDescriptor.ServiceKey` is set. If it is, we can safely ignore that descriptor.

For more information on keyed services, see the dotnet/runtime thread here: https://github.com/dotnet/runtime/issues/64427 and the PR here: https://github.com/dotnet/runtime/pull/87183.

Fixes #2604

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
Thanks @ReubenBond 

LGTM

**Comment by adityamandaleeka** [comment]
Can this be merged now?

**Review by mp-jrc — APPROVED** [review]

**Comment by onionhammer** [comment]
This seems like something that should be fixed sooner rather than later...

**Review by jennyf19 — APPROVED** [review]
:shipit: 
Thanks for the contribution @ReubenBond

**Comment by vijuhe** [comment]
Can this be released now or very soon at least? There is still one open feature in the release 2.17.1. Can the release be done without it?

**Comment by jennyf19** [comment]
@vijuhe we are testing the 2.17.1. It should be out later today PST.

**Comment by jennyf19** [comment]
Included in [2.17.1](https://github.com/AzureAD/microsoft-identity-web/releases/tag/2.17.1) Thanks @ReubenBond

**Pull request merged**
