### PR TITLE
Bugfix #749  Claim Actions Missing & Not Running

### PR DESCRIPTION
**Pull request by warrenbuckley**
Hello :wave: @jennyf19 
I believe this PR will fix the following issue #749 where ClaimActions are not run if you alter these when setting up Microsoft.Identity.Web in configuration/options.

I have unable to test this easily with my own code project, but with ClaimActions totally missing in the MergedOptions class I would believe this is the problem that myself and others are having.

Look forward to your feedback and input

Thanks,
Warren :)

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Is anyone from this team/repo likely to consider or comment on this PR, as I feel like I am in limbo with this.
Pinging the two people I can see making commits or comments in PRs in the hope I can get some input or feedback @jennyf19  & @pmaytak 

Thanks,
Warren 😄

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @warrenbuckley 

@jennyf19. We can merge to master, and also take in rel/v2.

**Comment by jennyf19** [comment]
Thanks @warrenbuckley - will take a look at this today. Thanks for your patience!

**Comment by warrenbuckley** [comment]
Thanks @jennyf19 & @jmprieur its good to know that this has been merged in.
Do you know when and what version my fix will be in?

Would it be possible for this PR to be marked as part of my Hacktoberfest contribution please?
Reading the site, it seems you as maintainers would need to add a label of `HACKTOBERFEST-ACCEPTED` to this PR

**Comment by jennyf19** [comment]
That's awesome! I've added the label.

**Pull request merged**
