### PR TITLE
Add a test for Jwt bearer options length

### PR DESCRIPTION
**Pull request by westin-m**

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @westin-m

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @westin-m 

We also need to fix anything here? 
https://github.com/AzureAD/microsoft-identity-web/blob/1c65d4a36e2155af04a4fa3b8a0a530f5aa3c121/src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/JwtBearerOptionsMerger.cs#L4

What are the new properties? Do they need to be in MergedOptions (I would think not, but it would be great to confirm)

**Comment by westin-m** [comment]
> What are the new properties?

The same new ones in OIDC; TokenHandlers, UseSecurityTokenValidators, and TimeProvider.

**Pull request merged**
