### PR TITLE
add net461 target for cache extensions

### PR DESCRIPTION
**Pull request by jennyf19**
@jmprieur as discussed

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
This is awesome @jennyf19, and this opens the way to delivering even more value for the ASP.NET customers.

@henrik-me : is it an option to support .NET 4.7.2 instead of .NET 4.6.1 ? this would also give us the certificate management with only one line of conditional compilation (with 4.6.1 the crypto is a bit different)

**Comment by henrik-me** [comment]
> This is awesome @jennyf19, and this opens the way to delivering even more value for the ASP.NET customers.
> 
> @henrik-me : is it an option to support .NET 4.7.2 instead of .NET 4.6.1 ? this would also give us the certificate management with only one line of conditional compilation (with 4.6.1 the crypto is a bit different)

4.7.2 is recommended in many ways. Not sure every one is there yet though and what the timeline will be (probably most by end of CY). Will require a bit of investigation on current usages.

Perhaps we can start with 4.7.2?

**Comment by jennyf19** [comment]
@henrik-me @jmprieur ok. thanks.

**Review by henrik-me — APPROVED** [review]
:shipit:

**Comment by henrik-me** [comment]
perhaps a utest validating that this the expected is available for the 4.7.2 target.

**Comment by jmprieur** [comment]
We could even expose the certificate management (including getting them from keyVault), by changing one line in DefaultCertificateLoader.cs:

line 97 
from `string[] segments = certificate.SecretId.AbsolutePath.Split('/', StringSplitOptions.RemoveEmptyEntries);``
to `string[] segments = certificate.SecretId.AbsolutePath.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);`

**Comment by jmprieur** [comment]
@jennyf19 : tested with https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/pull/43
:shipit:

**Comment by jennyf19** [comment]
i'm going to add a test app instead. so we can verify all the classes taht are added e2e.

---
In reply to: [720773691](https://github.com/AzureAD/microsoft-identity-web/pull/737#issuecomment-720773691) [](ancestors = 720773691)

**Comment by jennyf19** [comment]
maybe in a next PR?

---
In reply to: [721111217](https://github.com/AzureAD/microsoft-identity-web/pull/737#issuecomment-721111217) [](ancestors = 721111217)

**Comment by henrik-me** [comment]
I don't really like the test apps for something like this, but can be clarified as required validation step when checking the API. 
I would prefer a utest project that validates this. We should not require any manual validation of this. 
Also the sample should demonstrate the usage of this (I believe JM already made some of those changes to the sample)

---
In reply to: [721338397](https://github.com/AzureAD/microsoft-identity-web/pull/737#issuecomment-721338397) [](ancestors = 721338397,720773691)

**Comment by jmprieur** [comment]
yes, this is demonstrated in the sample: https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/pull/43
I've also updated the release spreadsheet

**Comment by jennyf19** [comment]
@henrik-me https://github.com/AzureAD/microsoft-identity-web/pull/754 for adding test.

**Pull request merged**
