### PR TITLE
Move type out of aspnetcore folder

### PR DESCRIPTION
**Pull request by keegan-caruso**
conditional compile for targets

### CODE REVIEW

**Comment by jmprieur** [comment]
@keegan-caruso : I would have also expected a change in the csproj?

**Comment by keegan-caruso** [comment]
@jmprieur sorry I don't follow, what change would that be?

**Comment by jmprieur** [comment]
Move the `MicrosoftIdentityAppCallsWebApiAuthenticationBuilder.cs` from the `AspNetCore` folder to the main folder of the project?

**Comment by keegan-caruso** [comment]
I did do that, github UI is just showing it as a rename.

https://github.com/AzureAD/microsoft-identity-web/blob/b9b4c501ad50847bf750c932eb1d12922fcfaa84/src/Microsoft.Identity.Web.TokenAcquisition/MicrosoftIdentityAppCallingWebApiAuthenticationBuilder.cs

Since it is in the root of the project folder, it is getting added to all of the targets now.

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by westin-m — APPROVED** [review]

**Pull request merged**
