### PR TITLE
update target framework to include cert for net fwk

### PR DESCRIPTION
**Pull request by jennyf19**

### CODE REVIEW

**Comment by henrik-me** [comment]
Looks great, seems to include stuff relevant for certs in the .net 4.7.2 target but otherwise no changes (assuming the utests are running both for core and netfwk?).

**Review by henrik-me — APPROVED** [review]
:shipit:

**Comment by jennyf19** [comment]
@henrik-me yes, i added the cert tests to net472.

**Comment by henrik-me** [comment]
ack, I didn't validate that the tests actually ran :)

---
In reply to: [775521862](https://github.com/AzureAD/microsoft-identity-web/pull/940#issuecomment-775521862) [](ancestors = 775521862)

**Pull request merged**
