### PR TITLE
fix blazor null httpcontext when using Azure SignalR

### PR DESCRIPTION
**Pull request by jennyf19**
fix for #392 
cc: @DanielMannInCycle @javiercn

### CODE REVIEW

**Comment by DanielMannInCycle** [comment]
When I integrated this code into my repro case, I started receiving this exception:
`MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.`

When I wrapped the calls in a `try`/`catch` that calls `HandleException`, I get a `NullReferenceException`: >	```Microsoft.Identity.Web.dll!Microsoft.Identity.Web.MicrosoftIdentityConsentAndConditionalAccessHandler.HandleException(System.Exception exception) Line 140```

**Comment by jennyf19** [comment]
@DanielMannInCycle ok. thank you. i think the NavigationManager is null, so it's throwing a null ref here:
`string redirectUri = NavigationManager.Uri;`

Will take a look.

**Comment by DanielMannInCycle** [comment]
@jennyf19 This PR was merged with the issue I reported still occurring -- should I open a new issue to track that behavior?

**Comment by jennyf19** [comment]
@DanielMannInCycle no...we are still working on that issue as well. I think we're getting further along. If needed, we will open a new issue w/details and let you know.

**Comment by josheinstein** [comment]
In stepping through the debugger, it seems that MicrosoftIdentityConsentAndConditionalAccessHandler is trying to access NavigationManager before the MicrosoftIdentityServiceHandler has been instantiated, thus NavigationManager is still null. Can't NavigationManager be injected into the constructor instead of waiting for the circuit handler to set it? (I'm very new to Blazor, so my apologies if that's a stupid question.)

**Pull request merged**
