### PR TITLE
Ensure DownstreamWebApiOptions clone includes all properties.

### PR DESCRIPTION
**Pull request by rvplauborg**
Fix for issue I created: #1970

### CODE REVIEW

**Comment by rvplauborg** [comment]
@microsoft-github-policy-service agree

**Comment by rvplauborg** [comment]
Hopefully we can get this merged quickly, as it is a very small change and can help people who are hit by #1970

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks very much, @rvplauborg 

@jennyf19, I would take this one in master (and in rel/v2 too)

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Comment by jennyf19** [comment]
Thanks @rvplauborg appreciate the contribution!

**Pull request merged**
