### PR TITLE
Making GetClientAssertion method public

### PR DESCRIPTION
**Pull request by JoshLozensky**
This will support inheritance of ClientAssertionProviderBase so it can be used to make your own ClientAssertionProvider.

### CODE REVIEW

**Review by jmprieur — CHANGES_REQUESTED** [review]
.

**Review by jmprieur — COMMENTED** [review]
.

**Review by jennyf19 — APPROVED** [review]
Thanks @JoshLozensky :shipit:

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @JoshLozensky

**Pull request merged**
