### PR TITLE
rename MicrosoftGraph* to just MicrosoftGraph

### PR DESCRIPTION
**Pull request by jennyf19**
just a suggestion

### CODE REVIEW

**Comment by jennyf19** [comment]
@pmaytak I don't know what the question is...can you clarify? what do you mean by "matching it"?

**Comment by pmaytak** [comment]
> @pmaytak I don't know what the question is...can you clarify? what do you mean by "matching it"?

- I like `AddMicrosoftGraph` change.
- Currently we have .AddDownstreamWebApi**Service**. If we remove **ServiceClient** from the Graph call, we could remove **Service** from AddDownstreamWebApiService for consistency. Just a small thought.

**Comment by jennyf19** [comment]
oh wow! I had NO idea that's what you meant!!!! LOL!! I LOVE the idea. i actually just added it to this PR. I agree, I think removing "service" is awesome and does match things across the board now. great suggestion. this made me laugh a lot. :)

---
In reply to: [673867293](https://github.com/AzureAD/microsoft-identity-web/pull/451#issuecomment-673867293) [](ancestors = 673867293)

**Comment by jennyf19** [comment]
@jmprieur -> @pmaytak had an amazing idea for another name change, which i've added here (see above), just put it all in one PR. feel free to merge if you agree w/the naming changes.

**Comment by jmprieur** [comment]
Merging as this is easier to work on the templates

**Pull request merged**
