### PR TITLE
Blazor Server Incremental Consent Issue

### PR DESCRIPTION
**Pull request by Shama-K**

### CODE REVIEW

**Comment by jennyf19** [comment]
@Shama-K i don't have the context for this, what exactly is this fixing & how should we test it? thank you.

**Comment by Shama-K** [comment]
> @Shama-K i don't have the context for this, what exactly is this fixing & how should we test it? thank you.

@jennyf19, In Blazor server application when client app is requesting consent for API, it goes into infinite loop. I've shared fiddler trace in the email. 
Please find the steps to reproduce:
1. Clone [ms-identity-blazor-server](https://github.com/Azure-Samples/ms-identity-blazor-server) repo and go to [MyOrg](https://github.com/Azure-Samples/ms-identity-blazor-server/tree/main/WebApp-your-API/MyOrg) project.
2. Remove scope from this code in Startup.cs, by updating as below:
services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
             .EnableTokenAcquisitionToCallDownstreamApi()
              .AddInMemoryTokenCaches();
3. Run the application and Sign-in. Select ToDoList and it will go into infinite loop instead of providing consent screen.

**Comment by jennyf19** [comment]
thank you @Shama-K . appreciate the additional info. i will try it out today. thanks.

**Comment by jennyf19** [comment]
@Shama-K sorry this took so long to review, but i wanted to test e2e and understand a few things first. I think we should use the `OAuthChallengeProperties` directly instead of the `AuthenticationProperties` because we can set the scope value directly there. Also, let's rename "properties" to "items" to match the asp .net value. 

finally, we need to test this in the other scenarios as well, to make sure things still behave the same. If your team can help w/that, and keep track of what has been tested, we can get this merged faster. 

my suggestion (if you'd rather i do the changes, lmk)
```csharp
string scheme = OpenIdConnectDefaults.AuthenticationScheme;
Dictionary<string, string?> items = new Dictionary<string, string?>
{
    { Constants.Claims, claims },
    { Constants.Policy, policy },
};
Dictionary<string, object?> parameters = new Dictionary<string, object?>
{
    { Constants.LoginHint, loginHint },
    { Constants.DomainHint, domainHint },
};

OAuthChallengeProperties oAuthChallengeProperties = new OAuthChallengeProperties(items, parameters);
oAuthChallengeProperties.Scope = scope?.Split(" ");
oAuthChallengeProperties.RedirectUri = redirectUri;

return Challenge(
    oAuthChallengeProperties,
    scheme);
```

**Review by jennyf19 — CHANGES_REQUESTED** [review]
see above.

**Comment by jennyf19** [comment]
@jmprieur can you give us specifics on what you'd like tested manually (ex. platforms)? thx.

**Review by jennyf19 — APPROVED** [review]
:shipit: awesome. thanks @Shama-K

**Review by jmprieur — APPROVED** [review]
LGTM

We want to test this with 
- MVC web apps (AAD and B2C)
-  Razor web apps (AAD and B2C)

**Comment by jennyf19** [comment]
@Shama-K i'm going to merge this, as it will be easier for us to test. this will be in 1.4.2 release, in January. thanks so much.

**Comment by jennyf19** [comment]
@Shama-K can you open an issue for this fix? and link it here? thank you.

**Pull request merged**
