### PR TITLE
set name claim in web api

### PR DESCRIPTION
**Pull request by jennyf19**
#408 found while testing the OBO stuff.

cc: @jmprieur

### CODE REVIEW

**Comment by jennyf19** [comment]
@jmprieur I didn't check that yet. will do.

**Comment by jmprieur** [comment]
Do you mind proposing a better fix, @pmaytak  ?

**Comment by jennyf19** [comment]
@jmprieur I'll just use `.GetDispalyName()` in the controller and we can revisit this later. it's not high-priority.

**Comment by jmprieur** [comment]
Good idea, @jennyf19 
thanks for the heads-up @pmaytak.

let's take the time to do the right thing here (not needed for this release as there is a good solution for the test apps/customer apps)

**Comment by pmaytak** [comment]
@jennyf19 @jmprieur Yes, I'll create a lower priority issue to revisit this.

**Comment by jennyf19** [comment]
I had already created an issue here: https://github.com/AzureAD/microsoft-identity-web/issues/408 and moved it to a general project board under a later milestone.

**Pull request merged**
