### PR TITLE
Honor redirect a/AccountController

### PR DESCRIPTION
**Pull request by jennyf19**
needs a little more testing, but have some some w/the dev apps.
#760

### CODE REVIEW

**Comment by pmaytak** [comment]
Should this change be also applied to `EditProfile` and `ResetPassword`, since we're redirecting to root there also?

**Comment by jmprieur** [comment]
what does this mean @pmaytak: what do you suggest.? (how does this concretely impact this draft PR?)

**Comment by pmaytak** [comment]
@jmprieur 

For example, add the `redirectUri` argument to `EditProfile` action.
```csharp
[HttpGet("{scheme?}/{redirectUri?}")]
public IActionResult EditProfile([FromRoute] string scheme, [FromQuery] string redirectUri)
```
 Because the current behavior is
- Go to a non root page, like `/TodoList`.
- Go through the `edit profile` flow.
- We redirect to root `/`, instead of where the user was before.

**Comment by jmprieur** [comment]
Thanks for providing the full explanation, @pmaytak. This is useful.

This think a customer was trying to do that at some point.
@jennyf19 : would you mind updating the EditProfile as well. I'm not too sure for reset password as it's an interrupt from the sign-in flow. We'd need to test thorughly.

**Comment by jennyf19** [comment]
thanks. yes was wondering about b2c when testing and was going to bring it up in stand-up today.

**Comment by sven5** [comment]
@jennyf19 
When is this included in a release?

**Pull request closed without merging**
