### PR TITLE
Display error messages when run under Development

### PR DESCRIPTION
**Pull request by twsouthwick**
Currently, if an error occurs, the message shown says to run under Development to show more details. However, this occurs even when run under Development. This change uses TempData to display the error if available, which defaults to when run under development.

### CODE REVIEW

**Comment by twsouthwick** [comment]
Build is failing for something that appears unrelated (step: Instal KeyVault secrets)

**Comment by jmprieur** [comment]
Thanks for reporting @twsouthwick 
This is fixed

**Comment by jennyf19** [comment]
thanks @twsouthwick we will take a look at your PR.

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Comment by jennyf19** [comment]
thanks @twsouthwick this will go into our next release, which should be later this week or early next week.

**Pull request merged**
