### PR TITLE
Bump to MSAL 4.64.1

### PR DESCRIPTION
**Pull request by bgavrilMS**
Id.Web always needs to be on the latest MSAL. Otherwise we can't investigate issues.

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @bgavrilMS 

No reference to remove? (like wilson.abstractions)?

**Comment by jmprieur** [comment]
> Id.Web always needs to be on the latest MSAL. Otherwise we can't investigate issues.

It should be in the MSAL.NET release process then!

**Comment by bgavrilMS** [comment]
> LGTM Thanks @bgavrilMS
> 
> No reference to remove? (like wilson.abstractions)?

Thanks @jmprieur .. Id.Web.TokenCache does not depend directly on wilson.abstractions, but through MSAL. And MSAL still uses it (e.g. for logging). Did you mean anything else?

image

**Comment by jmprieur** [comment]
no. that's all. Was checking

**Review by jmprieur — APPROVED** [review]

**Review by keegan-caruso — APPROVED** [review]

**Comment by jennyf19** [comment]
> > Id.Web always needs to be on the latest MSAL. Otherwise we can't investigate issues.
> 
> It should be in the MSAL.NET release process then!

The MSAL team could provide the PRs for when they release and we don't generally take ones that are PCA Only with no CCA improvements.

**Pull request merged**
