### PR TITLE
remove netcoreapp 3.1

### PR DESCRIPTION
**Pull request by jennyf19**
#2262

### CODE REVIEW

**Comment by brentschmaltz** [comment]
Did we still need netcoreapp3.1 in ProjectTemplates?

**Review by pmaytak — APPROVED** [review]

**Comment by pmaytak** [comment]
CompatibilitySuppressions need to be regenerated also?

**Comment by jennyf19** [comment]
> Did we still need netcoreapp3.1 in ProjectTemplates?
> 
> And tools.

didn't find any tools on netcoreapp3.1 and after talking with JM we will not touch the project templates now

**Comment by jennyf19** [comment]
> CompatibilitySuppressions need to be regenerated also?

yes, done.

**Comment by brentschmaltz** [comment]
I found netcoreapp3.1 her:
https://github.com/AzureAD/microsoft-identity-web/blob/792c807af1ae42d321bffb10c2a6196ce33870e3/tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidation/CrossPlatformValidation.csproj#L4

**Comment by jennyf19** [comment]
> I found netcoreapp3.1 here:
> 
> https://github.com/AzureAD/microsoft-identity-web/blob/792c807af1ae42d321bffb10c2a6196ce33870e3/tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidation/CrossPlatformValidation.csproj#L4

done. thank you. sorry about that

**Review by pmaytak — APPROVED** [review]

**Comment by jennyf19** [comment]
> found one more 3.1 here:
> 
> https://github.com/AzureAD/microsoft-identity-web/blob/a5e3e43ef6f4e94246c9a35ae591163e0c76995c/tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj#L22

done. these are JM's tools...not shipped w/the product. just FYI.

**Pull request merged**
