### PR TITLE
honor redirect after sign-in

### PR DESCRIPTION
**Pull request by jennyf19**
#760

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @jennyf19

**Comment by satishrabari** [comment]
Hi, Would you please help me with the following things?
I want to redirect to account/logincallback URL after successful login. 
Where I put the redirect URL for this?

**Comment by jmprieur** [comment]
@satishrabari, did you see: https://github.com/AzureAD/microsoft-identity-web/wiki/Customization#redirect-to-a-particular-page-after-sign-in ?

**Comment by satishrabari** [comment]
Thanks @jmprieur 
I want to configure using startup.cs .
Is it possible?

**Comment by jmprieur** [comment]
@satishrabari that would be a question for the ASP.NET Core team. (https://github.com/aspnet/aspnetcore). In your case the user challenge happens automatically. I don't really know how to parametrize it

**Comment by satishrabari** [comment]
Thanks @jmprieur  for the quick response.
I will ask questions to the ASP.NET Core team.

**Pull request merged**
